In [2]:
import pandas as pd

df = pd.read_csv('LADECv1-2019.csv')
df

,id_master,c1,c2,stim,obs,obsc1,obsc2,stimlen,c1len,c2len,...,Juhasz_tran,st_c1_mean,st_c2_mean,Zipfvalue,c1_SLlg10wf,c2_SLlg10wf,c1_BLPbncfrequency,c1_BLPbncfrequencymillion,c2_BLPbncfrequency,c2_BLPbncfrequencymillion
0,3237,gad,about,gadabout,1,4,3,8,3,5,...,NaN,NaN,NaN,1.768955,1.4314,5.2677,28.0,0.280000,197116.0,1971.160000
1,4592,knock,about,knockabout,1,3,4,10,5,5,...,NaN,NaN,NaN,1.592864,3.5185,5.2677,1975.0,19.750000,197116.0,1971.160000
2,8231,turn,about,turnabout,1,19,7,9,4,5,...,NaN,4.452,2.813,2.333227,4.1940,5.2677,21026.0,210.259990,197116.0,1971.160000
3,6139,race,about,raceabout,1,4,1,9,4,5,...,NaN,NaN,NaN,NaN,3.4994,5.2677,7959.0,79.589996,197116.0,1971.160000
4,8331,walk,about,walkabout,1,2,5,9,4,5,...,NaN,4.594,2.733,2.246077,4.0418,5.2677,10441.0,104.410000,197116.0,1971.160000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8951,4515,junk,yards,junkyards,1,1,10,9,4,5,...,NaN,NaN,NaN,1.592864,2.8949,2.8814,623.0,6.230000,3678.0,36.779999
8952,6812,ship,yards,shipyards,1,10,9,9,4,5,...,NaN,NaN,NaN,2.570588,3.7028,2.8814,4729.0,47.290001,3678.0,36.779999
8953,2667,farm,yards,farmyards,1,10,6,9,4,5,...,NaN,NaN,NaN,1.592864,3.1855,2.8814,6913.0,69.129997,3678.0,36.779999
8954,1007,brick,yards,brickyards,1,8,12,10,5,5,...,NaN,NaN,NaN,NaN,2.7160,2.8814,1861.0,18.610001,3678.0,36.779999
8955,8892,zig,zag,zigzag,1,1,1,6,3,3,...,NaN,NaN,NaN,2.672045,1.3424,1.0414,NaN,NaN,NaN,NaN

In [5]:
df.columns

Index(['id_master', 'c1', 'c2', 'stim', 'obs', 'obsc1', 'obsc2', 'stimlen',
       'c1len', 'c2len', 'nparses', 'correctParse', 'ratingcmp', 'ratingC1',
       'ratingC2', 'isPlural', 'nc1_cmp', 'nc2_cmp', 'nc1_cmpnoplural',
       'nc2_cmpnoplural', 'sentiment_stim', 'sentiment_c1', 'sentiment_c2',
       'sentimentprobpos_stim', 'sentimentprobpos_c1', 'sentimentprobpos_c2',
       'sentimentprobneg_stim', 'sentimentprobneg_c1', 'sentimentprobneg_c2',
       'sentimentratioposneg_stim', 'sentimentratioposneg_c1',
       'sentimentratioposneg_c2', 'profanity_stim', 'profanity_c1',
       'profanity_c2', 'isCommonstim', 'isCommonC1', 'isCommonC2',
       'bg_boundary', 'bgJonesMewhort', 'bgSUBTLEX', 'bgFacebook', 'inSUBTLEX',
       'inBLP', 'inELP', 'inJuhaszLaiWoodcock', 'c1_inELP', 'c1_inBrysbaert',
       'c1_inWordnet', 'c1_inMMA', 'c2_inELP', 'c2_inBrysbaert',
       'c2_inWordnet', 'c2_inMMA', 'LSAc1c2', 'LSAc1stim', 'LSAc2stim',
       'stim_SLlg10wf', 'BLPbncfrequency', 'BLPbncfrequencymillion', 'BLPrt',
       'elp_ld_rt', 'elp_naming_mean_rt', 'c1c2_snautCos', 'c1stim_snautCos',
       'c2stim_snautCos', 'fbusfreq', 'fbukfreq', 'valence_stim', 'valence_c1',
       'valence_c2', 'concreteness_stim', 'concreteness_c1', 'concreteness_c2',
       'Juhasz_tran', 'st_c1_mean', 'st_c2_mean', 'Zipfvalue', 'c1_SLlg10wf',
       'c2_SLlg10wf', 'c1_BLPbncfrequency', 'c1_BLPbncfrequencymillion',
       'c2_BLPbncfrequency', 'c2_BLPbncfrequencymillion'],
      dtype='object')

In [8]:
df['isPlural'].value_counts()

0    6017
1    2939
Name: isPlural, dtype: int64

In [11]:
df_singular = df[df['isPlural'] == 0]
df_singular.sort_values(by='BLPbncfrequency', ascending=False)[['stim', 'BLPbncfrequency']].head(50)

            stim  BLPbncfrequency
5324     someone          18681.0
4599    chairman          11572.0
8049    software           9405.0
8126     railway           7287.0
8685     network           7258.0
8372   somewhere           7026.0
282     football           6703.0
2246     weekend           6315.0
1898    aircraft           6203.0
2970  background           6171.0
8373   meanwhile           4813.0
2322   breakfast           4456.0
6173     bedroom           4352.0
4614   spokesman           3965.0
3350   household           3943.0
8683   framework           3926.0
1508   landscape           3305.0
6380   landscape           3305.0
2024    birthday           3247.0
5899     airport           2920.0
4379    landlord           2700.0
6189    bathroom           2498.0
3276     nowhere           2362.0
6177   classroom           2249.0
8033    hardware           2076.0
4116    wildlife           1993.0
5242    midnight           1882.0
7661    lifetime           1833.0
3484    workshop           1814.0
6643    workshop           1814.0
8140     doorway           1661.0
1609   broadcast           1498.0
1437     goodbye           1488.0
2116   breakdown           1477.0
3957     midland           1475.0
4761   nightmare           1441.0
804     cupboard           1438.0
7672    meantime           1438.0
3139    forehead           1326.0
6574    sunshine           1313.0
4146    sunlight           1303.0
148     feedback           1282.0
7296  mainstream           1238.0
4135   highlight           1193.0
2783  girlfriend           1174.0
6469      offset           1129.0
2784   boyfriend           1093.0
4197     airline           1070.0
3984    mainland           1053.0
7678     wartime           1047.0